"""
QUICK REFERENCE: TextGrad MAS Framework
========================================

This file shows the essential API for using the framework.
"""

# ============================================================
# 1. BASIC USAGE - Linear Trajectory
# ============================================================

from core import trajectory_to_graph, compute_loss

# Your trajectory as a list of steps
steps = [
    {"role": "AgentA", "content": "Step A content..."},
    {"role": "AgentB", "content": "Step B content..."},
    {"role": "AgentC", "content": "Step C content (final answer)..."},
]

# Build graph (linear mode: A → B → C)
graph = trajectory_to_graph(
    steps=steps,
    problem="Your problem statement",
    ground_truth="Expected answer",
    mode="linear"  # or "full" for all-to-all connections
)

# Compute initial loss
loss_node = graph.get_loss()
initial_criticism = compute_loss(loss_node, "Expected answer", "Problem")

# Get prompts for backward pass
templates = graph.linearize(initial_criticism)

# Each template is a dict:
# {
#   'prompt': str,      # The full prompt to send to LLM
#   'output_node': Tensor,
#   'input_node': Tensor,
#   'step_idx': int,
# }


# ============================================================
# 2. MANUAL TESTING
# ============================================================

def export_for_manual_testing(templates, filename):
    """Export prompts to a file for copy-paste testing."""
    with open(filename, 'w') as f:
        for i, t in enumerate(templates):
            f.write(f"=== PROMPT {i+1} ===\n")
            f.write(f"Analyzing: Step {t['output_node'].step_idx} → Step {t['step_idx']}\n\n")
            f.write(t['prompt'])
            f.write("\n\n--- YOUR RESPONSE ---\n\n\n")


# ============================================================
# 3. AUTOMATED TESTING WITH LLM
# ============================================================

from core import BackwardExecutor, parse_response

def my_llm(prompt: str) -> str:
    """Your LLM function. Could be Claude API, OpenAI, local model, etc."""
    # Example with Anthropic:
    # response = client.messages.create(
    #     model="claude-sonnet-4-20250514",
    #     max_tokens=1000,
    #     messages=[{"role": "user", "content": prompt}]
    # )
    # return response.content[0].text
    pass

# Create executor
executor = BackwardExecutor(llm_fn=my_llm)

# Run backward pass (calls LLM for each edge)
results = executor.run(graph, initial_criticism)

# Get ranked suspects
ranked = executor.rank_nodes(graph)
top_3 = executor.get_top_suspects(graph, k=3)

print("Top suspects:")
for s in top_3:
    print(f"  Step {s['step_idx']} ({s['role']}): score={s['score']:.2f}")


# ============================================================
# 4. CUSTOM GRAPH CONSTRUCTION
# ============================================================

from core import Graph, Tensor

graph = Graph(problem="...", ground_truth="...")

# Add nodes with explicit predecessors
node0 = graph.add_node(value="...", role="Planner", step_idx=0)
node1 = graph.add_node(value="...", role="Executor", step_idx=1, predecessors=[node0])
node2 = graph.add_node(value="...", role="Checker", step_idx=2, predecessors=[node0, node1])

# Memory-aware pattern
memory_v1 = graph.add_node(value="Initial memory", role="Memory", step_idx=0)
action_1 = graph.add_node(value="Action output", role="Actor", step_idx=1, predecessors=[memory_v1])
memory_v2 = graph.add_node(value="Updated memory", role="Memory", step_idx=2, 
                           predecessors=[memory_v1, action_1])  # Memory depends on old + new info

graph.set_loss(memory_v2)


# ============================================================
# 5. CUSTOM BACKWARD TEMPLATES
# ============================================================

from core import register_backward_template

# Add a custom operation type
register_backward_template("database_query", """
You are analyzing a failure in a database query operation.

## Context
PROBLEM: {problem}
GROUND TRUTH: {ground_truth}

## Query Result (Step {output_idx})
```
{output_value}
```

Query was generated by (Step {input_idx}, {input_role}):
```
{input_value}
```

## Downstream Issue
{downstream_grad}

## Your Task
Analyze the database operation:
1. Was the SQL query malformed?
2. Was the correct table queried but wrong columns selected?
3. Was the filtering logic wrong?
4. Or was the query specification from upstream incorrect?

## Required Output Format:
ATTRIBUTION: [QUERY_SYNTAX | COLUMN_SELECTION | FILTER_LOGIC | SPEC_ERROR | NEITHER]
SEVERITY: [HIGH | MEDIUM | LOW | NONE]
CRITICISM: <Specific explanation>
""")


# ============================================================
# 6. PARSING LLM RESPONSES
# ============================================================

from core import parse_response

response = """
ATTRIBUTION: [EXTRACTION_ERROR]
SEVERITY: [HIGH]
CRITICISM: The web surfer extracted "bite" instead of "stare" because 
it misidentified the chorus boundary. The actual second chorus starts 
after "Looking out across the night-time", not after "Then let me take a bite".
"""

parsed = parse_response(response)
# parsed = {
#   'attribution': 'EXTRACTION_ERROR',
#   'severity': 'HIGH',
#   'severity_score': 1.0,
#   'criticism': 'The web surfer extracted...'
# }


# ============================================================
# 7. COMPLETE WORKFLOW
# ============================================================

def analyze_trajectory(steps, problem, ground_truth, llm_fn=None):
    """Complete workflow for analyzing a failed trajectory."""
    
    # Build graph
    graph = trajectory_to_graph(steps, problem, ground_truth)
    
    # Compute loss
    loss = compute_loss(graph.get_loss(), ground_truth, problem)
    
    if llm_fn is None:
        # Export for manual testing
        templates = graph.linearize(loss)
        export_for_manual_testing(templates, "prompts_output.txt")
        print(f"Exported {len(templates)} prompts to prompts_output.txt")
        return templates
    else:
        # Run automated analysis
        executor = BackwardExecutor(llm_fn)
        results = executor.run(graph, loss)
        suspects = executor.get_top_suspects(graph, k=3)
        
        print("Analysis complete. Top suspects:")
        for s in suspects:
            print(f"  Step {s['step_idx']} ({s['role']}): {s['score']:.2f}")
        
        return results, suspects
